ViewModels/HolidayView.cs
namespace OfficeTime.ViewModels
{
    public class HolidayView
    {
        public int Id { get; set; }

        public DateOnly? Datestart { get; set; }

        public DateOnly? Dateend { get; set; }

        public bool Pay { get; set; }

        public bool? Isleadapp { get; set; }

        public bool? Isdirectorapp { get; set; }

        public DateOnly? Datecreate { get; set; }

        public DateOnly? Dateapp { get; set; }

        public string? Emp { get; set; }

        public bool? Canceled { get; set; } 
    }
}

Pages/Admin/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DetailsModel(IMediator mediator) : PageModel
    {
        public EmployeeView Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

Pages/Admin/Employees/Edit.cshtml.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Extensions;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.Mapper;
using OfficeTime.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace OfficeTime.Pages.Admin.Employees
{
    public class EditModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public EmployeeView Employee { get; set; } = default!;
        [BindProperty]
        public List<PostView> ListPosts { get; set; }
        public SelectList Posts { get; set; }
        public List<SelectListItem> Roles { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }

            Employee = employee;

            var resultPost = await mediator.Send(new GetPostQuery());
            ListPosts = resultPost.Response;
            Posts = new SelectList(ListPosts, nameof(PostView.Id), nameof(PostView.Name));
            Roles = (Enum.GetValues(typeof(RoleAccess)).Cast<RoleAccess>().Select(
                e => new SelectListItem() { Text = e.ToString(), Value = e.ToString() })).ToList();
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdateEmployeeCommand
            {
                Id = Employee.Id,
                Fio = Employee.Fio,
                Telegram = Employee.Telegram,
                Yandex = Employee.Yandex,
                Datebirth = Employee.Datebirth?.ToDateTime(new TimeOnly()),
                Datestart = Employee.Datestart?.ToDateTime(new TimeOnly()),
                Password = Convert.ToBase64String(Employee.Password.ToSHA256()),
                PostId = Convert.ToInt32(Employee.Post),
                RoleId = Convert.ToInt32(Employee.Role),
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Holidays/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Holidays
{
    public class DetailsModel(IMediator mediator) : PageModel
    {
        public HolidayView HolidayView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetHolidaysQuery
            {
                Id = id
            });

            var holidayview = result.Response.FirstOrDefault();

            if (holidayview == null)
            {
                return NotFound();
            }
            else
            {
                HolidayView = holidayview;
            }
            return Page();
        }
    }
}

Pages/Admin/Holidays/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace OfficeTime.Pages.Admin.Holidays
{
    public class EditModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public HolidayView HolidayView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetHolidaysQuery
            {
                Id = id
            });

            var holidayview = result.Response.FirstOrDefault();

            if (holidayview == null)
            {
                return NotFound();
            }
            HolidayView = holidayview;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdateHolidayCommand
            {
                Id = HolidayView.Id,
                Datestart = HolidayView.Datestart,
                Dateend = HolidayView.Dateend,

                Pay = HolidayView.Pay,

                Isleadapp = HolidayView.Isleadapp,

                Isdirectorapp = HolidayView.Isdirectorapp,

                Dateapp = HolidayView.Dateapp,

                Empid = 0 //todo: Session
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Holidays/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Goldev.Core.Attributes;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.GenerationModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Holidays
{
    public class IndexModel(IMediator mediator) : PageModel
    {
        public IList<HolidayView> HolidayView { get;set; } = default!;
        public DateTime DateStart { get; set; }
        public DateTime DateEnd { get; set; }

        public async Task OnGetAsync(DateTime? datestart, DateTime? dateEnd)
        {
            var result = await mediator.Send(new GetHolidaysQuery());
            if (datestart.HasValue && dateEnd.HasValue)
            {
                HolidayView = result.Response.Where(h => h.Canceled != true && h.Datestart?.ToDateTime(new TimeOnly()) > datestart && h.Datestart?.ToDateTime(new TimeOnly()) < dateEnd).ToList();
            }
            else
            {
                HolidayView = result.Response.Where(h => h.Canceled != true).ToList();
            }
        }

        public async Task<IActionResult> OnPostAgree(IFormCollection form)
        {
            var holidayId = Convert.ToInt32(form["holidayId"].ToString());
            var isadmin = Convert.ToBoolean(form["isadmin"].ToString());
            await mediator.Send(new ApproveHolidayCommand
            {
                Id = holidayId,
                IsLead = !isadmin,
                Value = true
            });

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDisgree(IFormCollection form)
        {
            var holidayId = Convert.ToInt32(form["holidayId"].ToString());
            var isadmin = Convert.ToBoolean(form["isadmin"].ToString());
            await mediator.Send(new ApproveHolidayCommand
            {
                Id = holidayId,
                IsLead = !isadmin,
                Value = false
            });

            return RedirectToPage("./Index");
        }
        public async Task<IActionResult> OnPostCreateReport()
        {
            await mediator.Send(new GenerateHolidayCommand
            {
                Type = TypeEnum.PutHolidays
            });
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostCreateYear()
        {
            await mediator.Send(new GenerateHolidayCommand
            {
                Type = TypeEnum.HolidaysT7
            });
            return RedirectToPage("./Index");
        }

    }
}

Pages/Admin/Posts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Posts
{
    public class DetailsModel(IMediator mediator) : PageModel
    {
        public PostView PostView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetPostQuery
            {
                Id = id
            });

            var postview = result.Response.FirstOrDefault();

            if (postview == null)
            {
                return NotFound();
            }
            else
            {
                PostView = postview;
            }
            return Page();
        }
    }
}

Pages/Admin/Posts/Edit.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Posts
{
    public class EditModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public PostView PostView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetPostQuery
            {
                Id = id,
            });

            var postview =  result.Response.FirstOrDefault();
            if (postview == null)
            {
                return NotFound();
            }
            PostView = postview;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdatePostCommand
            {
                Id = PostView.Id,
                Name = PostView.Name,
                Rate = PostView.Rate,
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/LK/Employee/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DetailsLKModel(IMediator mediator) : PageModel
    {
        public EmployeeView Employee { get; set; } = default!;

        //TODO: SessionId
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

Pages/LK/Employee/Edit.cshtml.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace OfficeTime.Pages.Admin.Employees
{
    public class EditLKModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public EmployeeView Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }

            Employee = employee;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdateEmployeeCommand
            {
                Id = Employee.Id,
                Fio = Employee.Fio,
                Telegram = Employee.Telegram,
                Yandex = Employee.Yandex,
                Datebirth = Employee.Datebirth,
                Datestart = Employee.Datestart,
                Password = Employee.Password
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/LK/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Unicode;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Helpers;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DetailsLKModel(IMediator mediator,
                                IHttpContextAccessor _httpContextAccessor) : PageModel
    {
        public EmployeeView Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            int? id = _httpContextAccessor.HttpContext.Session.GetId();

            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(IFormCollection from)
        {
            var date = Convert.ToDateTime(from["date"].ToString());
            var id = _httpContextAccessor.HttpContext.Session.GetId();

            await mediator.Send(new DismissalCommand
            {
                Id = (int)id,
                Date = date,
            });

            return RedirectToPage("./Details");
        }

        public async Task<IActionResult> OnPostCancelAsync(IFormCollection from)
        {
            var id = _httpContextAccessor.HttpContext.Session.GetId();

            await mediator.Send(new DismissalCancelCommand
            {
                Id = (int)id
            });

            return RedirectToPage("./Details");
        }
    }
}

Pages/Admin/Holidays/Details.cshtml
@page
@model OfficeTime.Pages.Admin.Holidays.DetailsModel

@{
    ViewData["Title"] = "Информация";
}

<h1>Подробности об отпуске</h1>

<div>
    <h4>Отпуск</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Datestart) *@
            Дата начала
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Datestart)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Dateend) *@
            Дата окончания
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Dateend)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Pay) *@
            Вид
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Pay)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Isleadapp) *@
            Подтвержден лидом
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Isleadapp)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Isdirectorapp) *@
            Подтвержден руководителем
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Isdirectorapp)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Datecreate) *@
            ДАта создания
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Datecreate)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Dateapp) *@
            Дата подтверждения
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Dateapp)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.HolidayView.Emp) *@
            Сотрудник
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HolidayView.Emp)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.HolidayView.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Admin/Holidays/Edit.cshtml
@page
@model OfficeTime.Pages.Admin.Holidays.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>HolidayView</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HolidayView.Id" />
            <div class="form-group">
                <label asp-for="HolidayView.Datestart" class="control-label"></label>
                <input asp-for="HolidayView.Datestart" class="form-control" />
                <span asp-validation-for="HolidayView.Datestart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HolidayView.Dateend" class="control-label"></label>
                <input asp-for="HolidayView.Dateend" class="form-control" />
                <span asp-validation-for="HolidayView.Dateend" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HolidayView.Pay" class="control-label"></label>
                <input type="checkbox" asp-for="HolidayView.Pay" class="form-control" />
                <span asp-validation-for="HolidayView.Pay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HolidayView.Isleadapp" class="control-label"></label>
                <input asp-for="HolidayView.Isleadapp" class="form-control" />
                <span asp-validation-for="HolidayView.Isleadapp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HolidayView.Isdirectorapp" class="control-label"></label>
                <input asp-for="HolidayView.Isdirectorapp" class="form-control" />
                <span asp-validation-for="HolidayView.Isdirectorapp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HolidayView.Dateapp" class="control-label"></label>
                <input asp-for="HolidayView.Dateapp" class="form-control" />
                <span asp-validation-for="HolidayView.Dateapp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Holidays/Index.cshtml
@page
@model OfficeTime.Pages.Admin.Holidays.IndexModel

@{
    ViewData["Title"] = "График отпусков";
}

<h1>График отпусков</h1>

<p>
    <a asp-page="Create">Создать новый отпуск</a>
</p>

<form asp-page="./Index" method="get" class="row g-3">
    <label>Найти за период:</label>

    <div class="col-auto">
        <input type="date" name="dateStart" value="@Model.DateStart" class="form-control" />
    </div>
    <div class="col-auto">
        <input type="date" name="dateEnd" value="@Model.DateEnd" class="form-control" />
    </div>
    <div class="col-auto">
        <input type="submit" value="Найти" class="btn btn-primary" /> |
        <a asp-page="./Index">Вернуться к полному списку</a>
    </div>
</form>

@if(LoginModel.Role==Mapper.RoleAccess.ADMIN)
{
    <p>
        <form method="post">
            <button type="submit" class="btn btn-light" asp-page-handler="CreateReport">Сгенерировать приказ об отпусках на месяц</button>
        </form>
        <form method="post">
            <button type="submit" class="btn btn-light" asp-page-handler="CreateYear">Сгенерировать график отпусков на год</button>
        </form>

    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @* @Html.DisplayNameFor(model => model.HolidayView[0].Datestart) *@
                Дата начала
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.HolidayView[0].Dateend) *@
                Дата окончания
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.HolidayView[0].Pay) *@
                Тип
            </th>
            @if(LoginModel.Role == Mapper.RoleAccess.LEAD)
            {
                <th>
                    @* @Html.DisplayNameFor(model => model.HolidayView[0].Isleadapp) *@
                    Подтверждение лидом
                </th>
            }
            @if (LoginModel.Role == Mapper.RoleAccess.ADMIN)
            {
                <th>
                    @* @Html.DisplayNameFor(model => model.HolidayView[0].Isdirectorapp) *@
                    Подтверждение руководителем
                </th>
            }
            <th>
                @* @Html.DisplayNameFor(model => model.HolidayView[0].Datecreate) *@
                Дата создания
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.HolidayView[0].Dateapp) *@
                Дата подтверждения
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.HolidayView[0].Emp) *@
                Сотрудник
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.HolidayView) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Datestart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dateend)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pay)
            </td>
            @if(LoginModel.Role == Mapper.RoleAccess.LEAD)
                {
                    <td>
                        @if(item.Isleadapp.HasValue && item.Isleadapp == true)
                        {
                            <label>Согласован</label>
                        }
                        @if (item.Isleadapp.HasValue && item.Isleadapp == false)
                        {
                            <label>Отклонен</label>
                        }
                        else
                        {
                            <form method="post">
                                <input type="hidden" name="holidayId" id="holidayId" value=@item.Id  />
                                <input type="hidden" name="isadmin" id="isadmin"  value="false" />
                                <input type="submit" class="btn btn-info" id="btnSave" value="Согласовать" asp-page-handler="Agree"/>
                                <input type="submit" class="btn btn-danger id="btnCancel" value="Отклонить" asp-page-handler="Disgree" />
                            </form>
                        }
                    </td>
                }
                
                @if (LoginModel.Role == Mapper.RoleAccess.ADMIN)
                {
                    <td>
                        @if (item.Isdirectorapp.HasValue && item.Isdirectorapp == true)
                        {
                            <label>Согласован</label>
                        }
                        else
                        {
                            <form method="post">
                                <input type="hidden" name="holidayId" id="holidayId" value="@item.Id" />
                                <input type="hidden" name="isadmin" id="isadmin" value="true" />
                                <input type="submit" class="btn btn-info" id="btnSave" value="Согласовать" asp-page-handler="Agree" />
                                <input type="submit" class="btn btn-danger id="btnCancel" value="Отклонить" asp-page-handler="Disgree" />
                            </form>
                        }
                    </td>
                }
            <td>
                @Html.DisplayFor(modelItem => item.Datecreate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dateapp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emp)
            </td>
            <td>
                <a asp-page="./Details" asp-route-id="@item.Id">Детали</a>
            </td>
        </tr>
}
    </tbody>
</table>