ViewModels/EmployeeView.cs
using OfficeTime.Mapper;

namespace OfficeTime.ViewModels
{
    public class EmployeeView
    {
        public int Id { get; set; }

        public string Fio { get; set; }

        public string? Telegram { get; set; } = String.Empty;

        public string? Yandex { get; set; } = String.Empty;

        public DateOnly? Datebirth { get; set; }

        public DateOnly? Datestart { get; set; }

        public string? Post { get; set; }
        public string? Password { get; set; } = String.Empty;

        public bool IsDelete { get; set; }
        public DateOnly? DeleteDate { get; set; }
        public RoleAccess Role {  get; set; }
    }
}

Pages/Admin/Employees/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Extensions;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.Mapper;
using OfficeTime.ViewModels;
using Syncfusion.EJ2.Navigations;

namespace OfficeTime.Pages.Admin.Employees
{
    public class CreateModel(IMediator mediator) : PageModel
    {
        public async Task<IActionResult> OnGetAsync()
        {
            var resultPost = await mediator.Send(new GetPostQuery());
            ListPosts = resultPost.Response;
            Posts = new SelectList(ListPosts, nameof(PostView.Id), nameof(PostView.Name));
            Roles = (Enum.GetValues(typeof(RoleAccess)).Cast<RoleAccess>().Select(
                e => new SelectListItem() { Text = e.ToString(), Value = e.ToString() })).ToList();
            return Page();
        }

        [BindProperty]
        public EmployeeView Employee { get; set; } = default!;
        public List<PostView> ListPosts { get; set; }
        public SelectList Posts {  get; set; }
        public List<SelectListItem> Roles {  get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var result = await mediator.Send(new CreateEmployeeCommand
            {
                Id = Employee.Id,
                Fio = Employee.Fio,
                Telegram = Employee.Telegram,
                Yandex = Employee.Yandex,
                Datebirth = Employee.Datebirth?.ToDateTime(new TimeOnly()),
                Datestart = Employee.Datestart?.ToDateTime(new TimeOnly()),
                Password = Convert.ToBase64String(Employee.Password.ToSHA256()),
                PostId = Convert.ToInt32(Employee.Post),
                RoleId = Convert.ToInt32(Employee.Role)
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DeleteModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public EmployeeView Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();

            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await mediator.Send(new DeleteEmployeeCommand
            {
                Id = id.Value
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DetailsModel(IMediator mediator) : PageModel
    {
        public EmployeeView Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

Pages/Admin/Employees/Edit.cshtml.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Extensions;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.Mapper;
using OfficeTime.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace OfficeTime.Pages.Admin.Employees
{
    public class EditModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public EmployeeView Employee { get; set; } = default!;
        [BindProperty]
        public List<PostView> ListPosts { get; set; }
        public SelectList Posts { get; set; }
        public List<SelectListItem> Roles { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }

            Employee = employee;

            var resultPost = await mediator.Send(new GetPostQuery());
            ListPosts = resultPost.Response;
            Posts = new SelectList(ListPosts, nameof(PostView.Id), nameof(PostView.Name));
            Roles = (Enum.GetValues(typeof(RoleAccess)).Cast<RoleAccess>().Select(
                e => new SelectListItem() { Text = e.ToString(), Value = e.ToString() })).ToList();
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdateEmployeeCommand
            {
                Id = Employee.Id,
                Fio = Employee.Fio,
                Telegram = Employee.Telegram,
                Yandex = Employee.Yandex,
                Datebirth = Employee.Datebirth?.ToDateTime(new TimeOnly()),
                Datestart = Employee.Datestart?.ToDateTime(new TimeOnly()),
                Password = Convert.ToBase64String(Employee.Password.ToSHA256()),
                PostId = Convert.ToInt32(Employee.Post),
                RoleId = Convert.ToInt32(Employee.Role),
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Employees/Index.cshtml.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class IndexModel(IMediator mediator) : PageModel
    {
        public IList<EmployeeView> Employee { get; set; } = default!;

        public async Task OnGetAsync()
        {
            var result = await mediator.Send(new GetEmployeesQuery());
            Employee = result.Response;
        }
    }
}

Pages/Admin/Holidays/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Holidays
{
    public class DetailsModel(IMediator mediator) : PageModel
    {
        public HolidayView HolidayView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetHolidaysQuery
            {
                Id = id
            });

            var holidayview = result.Response.FirstOrDefault();

            if (holidayview == null)
            {
                return NotFound();
            }
            else
            {
                HolidayView = holidayview;
            }
            return Page();
        }
    }
}

Pages/Admin/Holidays/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace OfficeTime.Pages.Admin.Holidays
{
    public class EditModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public HolidayView HolidayView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetHolidaysQuery
            {
                Id = id
            });

            var holidayview = result.Response.FirstOrDefault();

            if (holidayview == null)
            {
                return NotFound();
            }
            HolidayView = holidayview;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdateHolidayCommand
            {
                Id = HolidayView.Id,
                Datestart = HolidayView.Datestart,
                Dateend = HolidayView.Dateend,

                Pay = HolidayView.Pay,

                Isleadapp = HolidayView.Isleadapp,

                Isdirectorapp = HolidayView.Isdirectorapp,

                Dateapp = HolidayView.Dateapp,

                Empid = 0 //todo: Session
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Posts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Posts
{
    public class DetailsModel(IMediator mediator) : PageModel
    {
        public PostView PostView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetPostQuery
            {
                Id = id
            });

            var postview = result.Response.FirstOrDefault();

            if (postview == null)
            {
                return NotFound();
            }
            else
            {
                PostView = postview;
            }
            return Page();
        }
    }
}

Pages/Admin/Posts/Edit.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Posts
{
    public class EditModel(IMediator mediator) : PageModel
    {
        [BindProperty]
        public PostView PostView { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetPostQuery
            {
                Id = id,
            });

            var postview =  result.Response.FirstOrDefault();
            if (postview == null)
            {
                return NotFound();
            }
            PostView = postview;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await mediator.Send(new UpdatePostCommand
            {
                Id = PostView.Id,
                Name = PostView.Name,
                Rate = PostView.Rate,
            });

            return RedirectToPage("./Index");
        }
    }
}

Pages/LK/Employee/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DetailsLKModel(IMediator mediator) : PageModel
    {
        public EmployeeView Employee { get; set; } = default!;

        //TODO: SessionId
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

Pages/LK/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Unicode;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeTime.DBModels;
using OfficeTime.Logic.Commands;
using OfficeTime.Logic.Helpers;
using OfficeTime.Logic.Queries;
using OfficeTime.ViewModels;

namespace OfficeTime.Pages.Admin.Employees
{
    public class DetailsLKModel(IMediator mediator,
                                IHttpContextAccessor _httpContextAccessor) : PageModel
    {
        public EmployeeView Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            int? id = _httpContextAccessor.HttpContext.Session.GetId();

            if (id == null)
            {
                return NotFound();
            }

            var result = await mediator.Send(new GetEmployeesQuery
            {
                Id = id,
            });

            var employee = result.Response.FirstOrDefault();
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(IFormCollection from)
        {
            var date = Convert.ToDateTime(from["date"].ToString());
            var id = _httpContextAccessor.HttpContext.Session.GetId();

            await mediator.Send(new DismissalCommand
            {
                Id = (int)id,
                Date = date,
            });

            return RedirectToPage("./Details");
        }

        public async Task<IActionResult> OnPostCancelAsync(IFormCollection from)
        {
            var id = _httpContextAccessor.HttpContext.Session.GetId();

            await mediator.Send(new DismissalCancelCommand
            {
                Id = (int)id
            });

            return RedirectToPage("./Details");
        }
    }
}

Pages/LK/Employees/Details.cshtml
@page
@using OfficeTime.Pages.Admin.Employees
@model DetailsLKModel

@{
    ViewData["Title"] = "Информация";
}

<h1>Информация о сотруднике</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Employee.Fio) *@
            ФИО
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Fio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Telegram)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Telegram)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Yandex)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Yandex)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Employee.Datebirth) *@
            Дата рождения
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Datebirth)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Employee.Datestart) *@
            Дата выхода
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Datestart)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Employee.Post) *@
            Должность
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Post)
        </dd>
    </dl>
    @if(Model.Employee.IsDelete)
    {
        <p>Вы подали заявление на увольнение от @Model.Employee.DeleteDate.Value</p>
        <form method="post" asp-page-handler="Cancel">
            <div class="form-group">
                <input type="submit" class="btn btn-danger" value="Отменить" />
            </div>
        </form>
    }
    else
    {
        <form method="post" class="row g-3">
            <div class="col-auto">
                <input type="date" id="date" name="date" class="form-control" />
            </div>
            <div class="col-auto">
                <input type="submit" class="btn btn-danger" value="Подать заявление на увольнение" />
            </div>
        </form>
    }
   
    
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Employee.Id">Изменить</a>
</div>

Pages/LK/Employees/Edit.cshtml
@page
@using OfficeTime.Pages.Admin.Employees
@model EditLKModel

@{
    ViewData["Title"] = "Редактировать";
}

<h1>Редактировать информацию о сотруднике</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Employee.Id" />
            <div class="form-group">
                <label asp-for="Employee.Fio" class="control-label">ФИО</label>
                <input asp-for="Employee.Fio" class="form-control" />
                <span asp-validation-for="Employee.Fio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.Telegram" class="control-label"></label>
                <input asp-for="Employee.Telegram" class="form-control" />
                <span asp-validation-for="Employee.Telegram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.Yandex" class="control-label"></label>
                <input asp-for="Employee.Yandex" class="form-control" />
                <span asp-validation-for="Employee.Yandex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.Datebirth" class="control-label">Дата рождения</label>
                <input asp-for="Employee.Datebirth" class="form-control" type="date" />
                <span asp-validation-for="Employee.Datebirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.Password" class="control-label">Пароль</label>
                <input type="password" asp-for="Employee.Password" class="form-control" />
                <span asp-validation-for="Employee.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Details">Вернуться к общей информации</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}